import { useEffect, useState, useCallback } from 'react';
import { getMyNotifications, markAsRead, markAllAsRead } from '../../api/notifications.api';
import { useNotif } from '../../context/NotifContext';
import { timeAgo } from '../../utils/formatDate';
import Button  from '../../components/ui/Button';
import Spinner from '../../components/ui/Spinner';
import Alert   from '../../components/ui/Alert';
import './NotificationsPage.css';

// ── Derive a display icon from the notification message text ─────────────────
// Messages embed emoji at the start when generated by the new triggers.
// Fall back to keyword matching for any older messages without emoji.
const getNotifIcon = (message = '') => {
  // 1. If the message already starts with an emoji, extract it
  const emojiMatch = message.match(/^(\p{Emoji_Presentation}|\p{Extended_Pictographic})/u);
  if (emojiMatch) return emojiMatch[0];

  // 2. Keyword fallback for legacy messages (older rows without emoji prefix)
  const m = message.toLowerCase();
  if (m.includes('discharg'))            return '🏥';
  if (m.includes('admitted') || m.includes('admission')) return '🛏️';
  if (m.includes('referral') && m.includes('new'))       return '🔄';
  if (m.includes('accepted'))            return '✅';
  if (m.includes('completed'))           return '🏅';
  if (m.includes('cancelled'))           return '❌';
  if (m.includes('triage') && m.includes('critical'))    return '🚨';
  if (m.includes('triage') && m.includes('urgent'))      return '⚠️';
  if (m.includes('triage'))              return '🟢';
  return '🔔';
};

// ── Colour accent based on message type ──────────────────────────────────────
const getAccentClass = (message = '') => {
  const m = message.toLowerCase();
  if (m.includes('critical'))  return 'notif-item--critical';
  if (m.includes('urgent'))    return 'notif-item--urgent';
  if (m.includes('cancelled')) return 'notif-item--cancelled';
  if (m.includes('discharg'))  return 'notif-item--discharge';
  return '';
};

// ── Main component ────────────────────────────────────────────────────────────
const NotificationsPage = () => {
  const { refreshNotifications } = useNotif();
  const [notifs,     setNotifs]     = useState([]);
  const [loading,    setLoading]    = useState(true);
  const [error,      setError]      = useState('');
  const [markingAll, setMarkingAll] = useState(false);

  const load = useCallback(() => {
    setLoading(true);
    getMyNotifications()
      .then((r) => { if (r.success) setNotifs(r.data); })
      .catch(() => setError('Failed to load notifications.'))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleMarkOne = async (id) => {
    try { await markAsRead(id); refreshNotifications(); load(); } catch (_) {}
  };

  const handleMarkAll = async () => {
    setMarkingAll(true);
    try { await markAllAsRead(); refreshNotifications(); load(); } catch (_) {}
    finally { setMarkingAll(false); }
  };

  const unread = notifs.filter((n) => !n.is_read).length;

  if (loading) return <Spinner />;

  return (
    <div className="notif-page">

      {/* Header */}
      <div className="page-header">
        <div>
          <h2 className="page-title">Notifications</h2>
          <p className="page-subtitle">
            {unread > 0 ? `${unread} unread` : 'All caught up'} · {notifs.length} total
          </p>
        </div>
        {unread > 0 && (
          <Button
            id="mark-all-read-btn"
            variant="secondary"
            onClick={handleMarkAll}
            loading={markingAll}
          >
            ✓ Mark All as Read
          </Button>
        )}
      </div>

      {error && <Alert type="error" message={error} onDismiss={() => setError('')} />}

      {/* Notification list */}
      <div className="notif-list">
        {notifs.length === 0 && (
          <div className="notif-empty">
            <span className="notif-empty__icon">🔔</span>
            <p className="text-muted">You have no notifications.</p>
          </div>
        )}

        {notifs.map((n) => {
          const icon   = getNotifIcon(n.message);
          const accent = getAccentClass(n.message);
          return (
            <div
              key={n.notification_id}
              className={`notif-item ${n.is_read ? '' : 'notif-item--unread'} ${accent}`}
            >
              {/* Icon avatar */}
              <div className="notif-item__avatar" aria-hidden="true">
                {icon}
              </div>

              {/* Body */}
              <div className="notif-item__body">
                <p className="notif-item__message">{n.message}</p>
                <span className="notif-item__time">{timeAgo(n.created_at)}</span>
              </div>

              {/* Mark read button — only on unread */}
              {!n.is_read && (
                <button
                  className="notif-item__mark-btn"
                  onClick={() => handleMarkOne(n.notification_id)}
                  title="Mark as read"
                  aria-label="Mark as read"
                >
                  ✓
                </button>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default NotificationsPage;
